remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
#theme: jekyll-theme-cayman

github:
  is_project_page: false

title: IGIP WG 2.2 Meeting 2025
description: Aachen
show_downloads: false
logo: aachen-small.jpg
